apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |

    server {
      listen 80;
      index index.php index.html;
      root /usr/share/nginx/html;
    }
    
  index.html: |
    <!doctype html>  
    <html>  
      <head>  
        <meta charset="utf-8">  
        <title>Desafio Utilizando K8S</title>  
      </head>  
      <body>  
        <h1>Code.education Rocks.</h1>
      </body>  
    </html>  
