apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocks-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rocks-nginx
  template:
    metadata:
      labels:
        app: rocks-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80

        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: nginx-conf
            readOnly: true
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: index-html
            readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: index-html
        configMap:
          name: nginx-conf
          items:
            - key: index.html
              path: index.html
      